stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "ocaml/opam-dev:ubuntu-16.04_ocaml-4.05.0_flambda"

compile_and_test:
  stage: build
  tags:
    - shared
  image: $DOCKER_IMAGE
  script:
    - opam update
    - opam pin add zlist . -n
    - opam install zlist -t --deps-only
    - dune build
    - dune build @doc
    - dune runtest
  artifacts:
    paths:
      - _build

pages:
  stage: deploy
  tags:
    - shared
  only:
    - master
  dependencies:
    - compile_and_test
  script:
    - mkdir public
    - cp -r _build/default/_doc/_html/* public
  artifacts:
    paths:
      - public
