stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: "registry.gitlab.com/jhaberku/zlist:fedora-33-4.12.0"

compile_and_test:
  stage: build
  tags:
    - shared
  image: $DOCKER_IMAGE
  script:
    - eval $(opam env)
    - opam update
    - opam pin -y -n add zlist .
    - opam install -y -t -d --deps-only zlist
    - dune subst
    - dune build
    - dune build @doc
    - dune runtest
  artifacts:
    paths:
      - _build

pages:
  stage: deploy
  tags:
    - shared
  only:
    - master
  dependencies:
    - compile_and_test
  script:
    - mkdir public
    - cp -r _build/default/_doc/_html/* public
  artifacts:
    paths:
      - public
